name: Krishna Kumar

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "@DEADLY_USERBOT"

          replace: "@Legend_Mr_Logos"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Initial commit'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: LEGEND-OS

          commit_user_email: Krishna045Jaiswal@gmail.com
